- id: letsencrypt-renewal
  alias: "Let's Encrypt Renewal"
  hide_entity: true
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt