homeassistant:
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages/
  whitelist_external_dirs:
    - '/tmp'

updater:
  reporting: true
  include_used_components: true

# Discover some devices automatically
discovery:

# Add person component
person:

# Stay up to date with latest Home Assistant components, introduced in 0.88.1
default_config:

scene: !include scenes.yaml