homeassistant:
  name: !secret homename
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  # Time Zones: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  packages: !include_dir_named packages/

updater:
  reporting: true
  include_used_components: true

# Discover some devices automatically
discovery:

# Add person component
person:

# Stay up to date with latest Home Assistant components, introduced in 0.88.1
default_config:
