title: !secret homename

excluded_entities:

views:
  - title: System
    icon: mdi:raspberrypi
    id: system
    cards:
      - type: vertical-stack
        cards:
          - type: sensor
            name: 1m load average
            entity: sensor.processor_use
            graph: line
            accuracy: 720
            line_width: 2
            line_color: "#3498db"
      - type: gauge
        title: Memory use
        entity: sensor.memory_use_percent
        unit_of_measurement: "%"
        severity:
          green: 0
          yellow: 70
          red: 85
      - type: gauge
        title: Disk space
        entity: sensor.disk_use_percent_config
        unit_of_measurement: "%"
        severity:
          green: 0
          yellow: 70
          red: 85

      - type: entities
        title: Links
        show_header_toggle: false
        entities:
          - type: weblink
            url: https://github.com/matt-FFFFFF
            icon: mdi:github-circle
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: script.github_pull
          tap_action: call-service
          service: script.turn_on
        - type: entity-button
          entity: script.restart_ha
          tap_action: call-service
          service: script.turn_on
      - type: entities
        entities:
          - entity: input_boolean.maintenance_mode
            name: Maintenance mode

      - type: glance
        title: Date & Time
        entities:
          - sensor.time
          - sensor.date
          - sensor.time_utc
          - sensor.last_boot
      
      - type: entities
        title: Z-Wave
        show_header_toggle: false
        entities:
          - zwave.aeotec_zw090_zstick_gen5_eu
          - script.zwave_on
          - script.zwave_off
          - script.zwave_include
  
  - title: Climate
    id: climate
    icon: mdi:thermostat
    cards:
      - type: thermostat
        entity: climate.hallway
      - type: glance
        show_header_toggle: false
        show_name: false
        title: Nest
        entities:
          - entity: binary_sensor.hallway_thermostat_has_leaf
            name:
            icon: mdi:leaf
          - entity: binary_sensor.hallway_thermostat_online
            name:
            icon: mdi:wifi
          - entity: sensor.hallway_thermostat_humidity
            name:
          - entity: sensor.hallway_thermostat_hvac_state
            name:
            icon: mdi:fire
          - entity: binary_sensor.wildown_gardens_away
            name:
            icon: mdi:exit-run
  
      - type: glance
        title: Temperatures
        entities:
          - entity: sensor.hallway_thermostat_target
            name: Target
          - entity: sensor.hallway_thermostat_temperature
            name: Actual
      
      - type: glance
        title: Climate Sensors
        show_header_toggle: true
        entities:
          - entity: sensor.hallway_temperature
            name: Hallway
          - entity: binary_sensor.home_occupied
            name: Occupied

          - entity: sensor.met_office_temperature
            name: Met office
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: binary_sensor.warmer_than_current_setpoint
            name: Warmer than current
          - type: entity-button
            entity: binary_sensor.warmer_than_day_setpoint
            name: Warmer than day
          - type: entity-button
            entity: binary_sensor.warmer_than_night_setpoint
            name: Warmer than night

      - type: entities
        title: Climate Controls
        show_header_toggle: true
        entities:
          - entity: input_number.outside_temp_offset
          - entity: input_number.daytime_heat_setpoint
          - entity: input_number.nighttime_heat_setpoint
          - entity: input_text.last_nest_mode
  
  - title: Rooms
    id: rooms
    icon: mdi:floor-plan
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Occupancy
            show_header_toggle: false
            columns: 8
            entities:
              - input_datetime.weekday_bedtime_on
              - input_datetime.weekday_bedtime_off
              - input_datetime.weekend_bedtime_on
              - input_datetime.weekend_bedtime_off
              - input_boolean.away_mode
              - input_boolean.guest_mode
              - input_boolean.holiday_mode
              - input_boolean.bedtime_mode
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: "## Lounge"
                  - type: horizontal-stack
                    cards:
                      - type: light
                        entity: light.loungedimmer
                        name: MAIN LIGHT
                      - type: entity-button
                        entity: switch.lounge_lamp
                        tap_action: toggle
                        icon: mdi:lightbulb
                  - type: media-control
                    entity: media_player.lounge_tv
                  - type: media-control
                    entity: media_player.living_room_hifi
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: "## Kitchen"
                  - type: media-control
                    title: Kitchen Sonos
                    entity: media_player.kitchen_sonos
              - type: vertical-stack
                title: Master Bedroom
                cards:
                  - type: markdown
                    content: "## Master Bedroom"
                  - type: media-control
                    title: Kitchen Sonos
                    entity: media_player.bedroom_soundbar_speaker

      

      
      - type: entities
        title: Phone Trackers
        show_header_toggle: false
        entities:
          - device_tracker.mattiphoneowntrk_iphone
          - device_tracker.beliphoneowntrk_iphone
  
  - title: Weather
    id: weather
    icon: mdi:weather-partlycloudy
    cards:
      - type: entities
        title: Met Office
        show_header_toggle: false
        entities:
          - sensor.met_office_feels_like_temperature
          - sensor.met_office_humidity
          - sensor.met_office_probability_of_precipitation
          - sensor.met_office_temperature
          - sensor.met_office_uv
          - sensor.met_office_visibility
          - sensor.met_office_visibility_distance
          - sensor.met_office_weather
          - sensor.met_office_wind_direction
          - sensor.met_office_wind_gust
          - sensor.met_office_wind_speed
      
      - type: entities
        title: Celestial Bodies
        show_header_toggle: false
        entities:
          - sensor.moon
          - sun.sun
          - binary_sensor.iss
  
  - title: Security
    icon: mdi:cctv
    cards:
      - type: glance
        title: Sensors
        entities:
          - entity: sensor.ring_hallway_wifi_signal_category
            name: Chime
          - entity: sensor.ring_hallway_volume
            name: Chime
          - entity: sensor.ring_front_door_wifi_signal_category
            name: Doorbell
          - entity: sensor.ring_front_door_volume
            name: Doorbell
          - entity: sensor.ring_front_door_last_motion
            name: Last motion
          - entity: sensor.ring_front_door_last_ding
            name: Last ding
          - entity: sensor.ring_front_door_battery
            name: Battery
          - entity: binary_sensor.ring_front_door_ding
            name: Bell
      - type: glance
        title: Motion
        entities:
          - entity: binary_sensor.ring_front_door_motion
            name: Front Door
          - entity: binary_sensor.hallway_motion_sensor
            name: Outside
      - type: picture-glance
        title: Ring
        camera_image: camera.front_door
        entities:
          - entity: sensor.ring_hallway_wifi_signal_category
            name: Chime
          - entity: sensor.ring_hallway_volume
            name: Chime
          - entity: sensor.ring_front_door_wifi_signal_category
            name: Doorbell
          - entity: sensor.ring_front_door_volume
            name: Doorbell
          - entity: sensor.ring_front_door_last_motion
            name: Last motion
          - entity: sensor.ring_front_door_last_ding
            name: Last ding
          - entity: sensor.ring_front_door_battery
            name: Battery
          - entity: binary_sensor.ring_front_door_ding
            name: Bell
