####################################################
#                                                  #
# This package automates the Nest HVAC controls    #
# DEPENDS ON Occupancy                             #
#                                                  #
####################################################

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_clientsecret

climate:
  platform: nest

sensor:
  - platform: mqtt
    name: Hallway Temperature
    state_topic: smartthings/Hallway Motion Sensor/temperature/state
    device_class: temperature
    retain: true

automation:
  - alias: Climate - away mode on
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
      for:
        minutes: 5
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: true

  - alias: Climate - away mode off
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'off'
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: false