####################################################
#                                                  #
# This package automates the Nest HVAC controls    #
#                                                  #
# Automates:                                       #
#   - away mode on house empty                     #
#   - eco mode when warm weather                   #
# DEPENDS ON Occupancy & Environment               #
#                                                  #
####################################################

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_clientsecret

climate:
  platform: nest

sensor:
  - platform: mqtt
    name: Hallway Temperature
    state_topic: smartthings/Hallway Motion Sensor/temperature/state
    device_class: temperature
    retain: true


input_text:
  last_nest_mode:
    name: Last Nest Mode
    min: 0
    max: 4
    pattern: '^eco$|^heat$|^off$'


input_number:
  outside_temp_offset:
    name: Outside Temperature Offset
    min: 0
    max: 10
    step: 1
    unit_of_measurement: °C

  daytime_heat_setpoint:
    name: Daytime Heat Setpoint
    min: 0
    max: 32
    step: 0.5
    unit_of_measurement: °C

  nighttime_heat_setpoint:
    name: Nighttime Heat Setpoint
    min: 0
    max: 32
    step: 0.5
    unit_of_measurement: °C


binary_sensor:
  - platform: template
    sensors:
      warmer_than_setpoint:
        friendly_name: Outside warmer than heat setpoint
        value_template: >-
          {{ (states.sensor.met_office_temperature.state | float)
            + (states.input_number.outside_temp_offset.state | int)
            >= states.sensor.hallway_thermostat_target.state | float }}


input_boolean:
  ha_owns_eco_mode:
    name: Home Assistant Owns Nest Eco/Away Mode
    icon: mdi:leaf


automation:
  - alias: Climate - update Nest on daytime heat setpoint change
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_number.daytime_heat_setpoint
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states.input_boolean.bedtime_mode.state == 'off' }}"
        - condition: template
          value_template: >-
            '{{ states.input_number.daytime_heat_setpoint.state | float 
              != states.climate.hallway.attributes.temperature | float }}'
        - condition: template
          value_template: "{{ states.climate.hallway.attributes.operation_mode == 'heat' }}"
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: '{{ states.input_number.daytime_heat_setpoint.state | float }}'

  - alias: Climate - update Nest on nighttime heat setpoint change
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_number.nighttime_heat_setpoint
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states.input_boolean.bedtime_mode.state == 'on' }}"
        - condition: template
          value_template: >-
            '{{ states.input_number.nighttime_heat_setpoint.state | float 
              != states.climate.hallway.attributes.temperature | float }}'
        - condition: template
          value_template: "{{ states.climate.hallway.attributes.operation_mode == 'heat' }}"
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: '{{ states.input_number.daytime_heat_setpoint.state | float }}'

  - alias: Climate - away mode on
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.away_mode
        to: 'on'
        for:
          minutes: 5
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: true
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.ha_owns_eco_mode

  - alias: Climate - away mode off
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.away_mode
        to: 'off'
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: false
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.ha_owns_eco_mode

  - alias: Climate - Update last known Nest mode
    initial_state: off
    trigger:
      - platform: state
        entity_id: sensor.hallway_thermostat_operation_mode
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.last_nest_mode
          value: '{{ states.sensor.hallway_thermostat_operation_mode.state }}'
  
  - alias: Climate - Initialise Nest on HA start
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: '00:00:15'
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.hallway
          operation_mode: '{{ states.input_text.last_nest_mode.state }}'
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: >-
            {%- if (states.input_boolean.bedtime_mode.state == 'on') -%}
              {{ states.input_number.nighttime_heat_setpoint.state | float }}
            {%- else -%}
              {{ states.input_number.daytime_heat_setpoint.state | float }}
            {%- endif -%}
      - delay: '00:00:15'
      - service: automation.turn_on
        data:
          entity_id: automation.climate__update_last_known_nest_mode
      - service: automation.trigger
        data:
          entity_id: automation.climate__update_last_known_nest_mode
      - service: automation.turn_on
        data:
          entity_id: automation.climate__enable_eco_mode_when_warm_weather
      - service: automation.trigger
        data:
          entity_id: automation.climate__enable_eco_mode_when_warm_weather
      - condition: template
        value_template: "{{ states.input_text.last_nest_mode.state == 'eco' }}"
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.ha_owns_eco_mode


  - alias: Climate - Update HA setpoint value when external update
    initial_state: on
    trigger:
      - platform: state
        entity_id: sensor.hallway_thermostat_target
    condition:
      - condition: template
        value_template: "{{ states.climate.hallway.attributes.operation_mode == 'heat' }}"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: >-
            {%- if (states.input_boolean.bedtime_mode.state == 'on') -%}
              input_number.nighttime_heat_setpoint
            {%- else -%}
              input_number.daytime_heat_setpoint
            {%- endif -%}
          value: '{{ states.sensor.hallway_thermostat_target.state | float }}'

  - alias: Climate - Reset homeassistant owns eco mode switch
    initial_state: on
    trigger:
      - platform: state
        entity_id: sensor.hallway_thermostat_operation_mode
        from: 'eco'
    action:
      - delay: '00:00:10'
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.ha_owns_eco_mode

  - alias: Climate - Enable eco mode when warm weather
    initial_state: off
    trigger:
      - platform: state
        entity_id: binary_sensor.warmer_than_setpoint
      - platform: state
        entity_id: sensor.hallway_thermostat_operation_mode
        to: 'heat'
        for:
          minutes: 2
    condition:
      - condition: template
        value_template: "{{ states.climate.hallway.attributes.operation_mode != 'off' }}"
    action:
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.hallway
          operation_mode: >-
            {%- if ((states.binary_sensor.warmer_than_setpoint.state == 'on')
              and
            (states.climate.hallway.attributes.operation_mode == 'heat')) -%}
              {{ states.climate.hallway.attributes.operation_list[2] }}
            {%- elif ((states.binary_sensor.warmer_than_setpoint.state == 'off')
              and
            (states.climate.hallway.attributes.operation_mode == 'eco')
              and
            (states.input_boolean.ha_owns_eco_mode.state == 'on')
              and
            (states.input_boolean.ha_owns_eco_mode.state == 'on')) -%}
              {{ states.climate.hallway.attributes.operation_list[1] }}
            {%- endif -%}
      - service_template: >-
          {%- if ((states.binary_sensor.warmer_than_setpoint.state == 'on')
            and
          (states.climate.hallway.attributes.operation_mode == 'heat')) -%}
            homeassistant.turn_on
          {%- elif ((states.binary_sensor.warmer_than_setpoint.state == 'off')
            and
          (states.climate.hallway.attributes.operation_mode == 'eco')
            and
          (states.input_boolean.ha_owns_eco_mode.state == 'on')) -%}
            homeassistant.turn_off
          {%- endif -%}
        entity_id: input_boolean.ha_owns_eco_mode