####################################################
#                                                  #
# This package automates the Nest HVAC controls    #
#                                                  #
# Automates:                                       #
#   - away mode on house empty                     #
#   - eco mode when warm weather                   #
# DEPENDS ON Occupancy & Environment               #
#                                                  #
####################################################

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_clientsecret

climate:
  platform: nest

sensor:
  - platform: mqtt
    name: Hallway Temperature
    state_topic: smartthings/Hallway Motion Sensor/temperature/state
    device_class: temperature
    retain: true
  

binary_sensor:
  - platform: template
    sensors:
      warmer_than_setpoint:
        friendly_name: Outside warmer than heat setpoint
        value_template: >-
          {{ states.sensor.met_office_feels_like_temperature | float >= states.sensor.hallway_thermostat_target | float }}


input_boolean:
  ha_owns_eco_mode:
    name: Home Assistant Owns Nest Eco Mode
    icon: mdi:leaf


automation:
  - alias: Climate - away mode on
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
      for:
        minutes: 5
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: true

  - alias: Climate - away mode off
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'off'
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: false

  - alias: Climate - Enable eco mode when warm weather
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.warmer_than_setpoint
      to: 'on'
    condition:
      - condition: template
        value_template: "{{ states.climate.hallway.attributes.operation_mode == 'heat' }}"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.ha_owns_eco_mode
      - service: climate.set_operation_mode
        data:
          entity_id: climate.hallway
          operation_mode: 'eco'

  - alias: Climate - Disable eco mode when colder weather
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.warmer_than_setpoint
      to: 'off'
    condition:
      - condition: template
        value_template: "{{ states.climate.hallway.attributes.operation_mode == 'eco' }}"
      - condition: template
        entity_id: "{{ states.binary_Sensor.iss.state == 'on' }}"
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.ha_owns_eco_mode
      - service: climate.set_operation_mode
        data:
          entity_id: climate.hallway
          operation_mode: 'heat'