####################################################
#                                                  #
# This package automates the Nest HVAC controls    #
#                                                  #
# Automates:                                       #
#   - away mode on house empty                     #
#   - eco mode when warm weather                   #
#   - day/night temperature setpoints              #
# DEPENDS ON Occupancy & Environment               #
#                                                  #
####################################################

## New cliamte management
## HVAC modes 'heat', 'off'
## Preset modes 'away', 'eco', 'none', 'Away and Eco'

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_clientsecret

climate:
  platform: nest

input_number:
  outside_temp_offset:
    name: Outside Temperature Offset
    min: 0
    max: 10
    step: 1
    unit_of_measurement: °C

  daytime_heat_setpoint:
    name: Daytime Heat Setpoint
    min: 0
    max: 32
    step: 0.5
    unit_of_measurement: °C

  nighttime_heat_setpoint:
    name: Nighttime Heat Setpoint
    min: 0
    max: 32
    step: 0.5
    unit_of_measurement: °C

binary_sensor:
  - platform: template
    sensors:
      warmer_than_current_setpoint:
        friendly_name: Outside warmer than current setpoint
        entity_id:
          - weather.met_office_bournemouth_southbourne_beach
          - input_number.outside_temp_offset
          - sensor.hallway_thermostat_target
        value_template: >-
          {{ state_attr('weather.met_office_bournemouth_southbourne_beach','temperature') | float
            + (states('input_number.outside_temp_offset') | int)
            >= states('sensor.hallway_thermostat_target') | float }}
      warmer_than_day_setpoint:
        friendly_name: Outside warmer than daytime 
        entity_id:
          - weather.met_office_bournemouth_southbourne_beach
          - input_number.outside_temp_offset
          - input_number.daytime_heat_setpoint
        value_template: >-
          {{ state_attr('weather.met_office_bournemouth_southbourne_beach','temperature') | float
            + (states('input_number.outside_temp_offset') | int)
            >= states('input_number.daytime_heat_setpoint') | float }}
      warmer_than_night_setpoint:
        friendly_name: Outside warmer than nighttime setpoint
        entity_id:
          - weather.met_office_bournemouth_southbourne_beach
          - input_number.outside_temp_offset
          - input_number.nighttime_heat_setpoint
        value_template: >-
          {{ state_attr('weather.met_office_bournemouth_southbourne_beach','temperature') | float
            + (states('input_number.outside_temp_offset') | int)
            >= states('input_number.nighttime_heat_setpoint') | float }}