
sun:

weather:
  platform: metoffice
  api_key: !secret metoffice_api_key

sensor:
  - platform: moon

input_boolean:
  dark:
    icon: mdi:brightness-4

binary_sensor:
  - platform: iss   
