homeassistant:
  customize:
    sensor.met_office_temperature:
      homebridge_visible: true
    sensor.met_office_wind_speed:
      homebridge_visible: true
    sensor.met_office_wind_direction:
      homebridge_visible: true
    sensor.met_office_wind_humidity:
      homebridge_visible: true

sun:

sensor:
  - platform: metoffice
    api_key: !secret metoffice_api_key
    monitored_conditions:
      - weather
      - temperature
      - feels_like_temperature
      - wind_speed
      - wind_direction
      - wind_gust
      - visibility
      - visibility_distance
      - uv
      - precipitation
      - humidity
  - platform: moon

# Override default home
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 150
    icon: mdi:home-variant
    track_ios: false

binary_sensor:
  - platform: iss
