
sun:

weather:
  - platform: metoffice
    api_key: !secret metoffice_api_key

sensor:
  - platform: moon
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
    hourly_forecast:
      - 0
    monitored_conditions:
      - cloud_cover

# Override default home
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 150
    icon: mdi:home-variant
    track_ios: false

binary_sensor:
  - platform: iss
