
sun:

weather:
  - platform: metoffice
    api_key: !secret metoffice_api_key

sensor:
  - platform: moon

# Override default home
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 150
    icon: mdi:home-variant
    track_ios: false

binary_sensor:
  - platform: iss
