homeassistant:
  customize_glob:
    sensor.loungedimmer_interval*:
      hidden: true
    sensor.loungedimmer_previous_reading*:
      hidden: true

group:
  lounge_lights:
    name: Lounge Lights
    entities:
      - light.loungedimmer
      - light.lounge_lamp

light:
  - platform: switch
    name: Lounge Lamp
    entity_id: switch.lounge_lamp

scene:
  - name: Lounge dim
    entities:
      light.loungedimmer: &dim
        state: on
        transition: 2
        brightness: 125
      light.lounge_lamp:
        state: off
  - name: Lounge bright
    entities:
      light.loungedimmer: &bright
        state: on
        transition: 4
        brightness: 255
      light.lounge_lamp:
        state: off
  - name: Lounge lamp
    entities:
      light.loungedimmer:
        state: off
        transition: 4
      light.lounge_lamp:
        state: on

automation:
  - alias: Lighting - lights off when away
    trigger:
      - platform: state
        entity_id: binary_sensor.home_occupied
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: group.all_lights

  - alias: Lighting - lights on when home
    trigger:
      - platform: state
        entity_id: binary_sensor.home_occupied
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.dark
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.lounge_dim
      - service: timer.start
        entity_id: timer.lounge_light_motion

  - alias: Lighting - lounge light on with movement
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_multi_sensor_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.dark
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.lounge_light_motion
      - service: timer.start
        entity_id: timer.lounge_light_motion
      - condition: state
        entity_id: group.lounge_lights
        state: 'off'
      - condition: state
        entity_id: media_player.lounge_tv
        state: 'off'
      - service: scene.turn_on
        entity_id: scene.lounge_dim

  - alias: Lighting - lounge light off with no movement
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.lounge_light_motion
    condition:
      - condition: state
        entity_id: input_boolean.bedtime_mode
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.loungedimmer

  - alias: Lighting - Lights on when dark
    trigger:
      - platform: state
        entity_id: input_boolean.dark
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.home_occupied
        state: 'on'
      - condition: state
        entity_id: binary_sensor.lounge_occupied
        state: 'on'
    action:
      - service: scene.turn_on
        data_template:
          entity_id: >-
            {%- if (states.media_player.lounge_tv.state == 'playing') -%}
              scene.lounge_lamp
            {%- else -%}
              scene.lounge_dim
            {%- endif -%}

  - alias: Lighting - Lights off at bedtime
    trigger:
      - platform: state
        entity_id: input_boolean.bedtime_mode
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.home_occupied
        state: 'on'
    action:
      - service: script.notify
        data:
          call_bedtime_mode_on: 1
          room: lounge
      - delay: '00:10:00'
      - service: light.turn_off
        entity_id: group.lounge_lights

  - alias: Lighting - Lamp light when tv on
    trigger:
      - platform: state
        entity_id: media_player.lounge_tv
        to: 'playing'
    condition:
      - condition: state
        entity_id: input_boolean.dark
        state: 'on'
      - condition: state
        entity_id: light.loungedimmer
        state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.lounge_lamp

  - alias: Lighting - Lounge lights off when unoccupied
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_occupied
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.bedtime_mode
        state: 'off'
    action:
      - delay: '00:02:00'
      - service: light.turn_off
        entity_id: group.lounge_lights

timer:
  lounge_light_motion:
    duration: '00:05:00'