homeassistant:
  customize_glob:
    sensor.loungedimmer_interval*:
      hidden: true
    sensor.loungedimmer_previous_reading*:
      hidden: true

group:
  lounge_lights:
    name: Lounge Lights
    entities:
      - light.loungedimmer
      - light.lounge_lamp

light:
  - platform: switch
    name: Lounge Lamp
    entity_id: switch.lounge_lamp_wall_plug_switch
