####################################################
#                                                  #
# This package creates a device that monitors who  #
# is at home, including a guest mode, and provides #
# modes that assist with automations.              #
#                                                  #
#  Depends on: Hardware                            #
####################################################

homeassistant:

  customize:
    group.all_automations:
      friendly_name: Automations
      icon: mdi:home-automation
      hidden: false
      hide_control: true
      confirm_controls_show_lock: true
      extra_badge:
        - entity_id: sensor.automation_on
        - entity_id: sensor.automation_all

    group.occupancy:
      hide_control: true
      control: hidden
      icon: mdi:home-account
    
    group.phone_trackers:
      state_card_mode: badges

    sensor.home_status:
      icon: mdi:home-map-marker
      homebridge_hidden: false

    input_boolean.holiday_mode:
      hide_control: true
      extra_badge:
        entity_id: input_boolean.holiday_mode


  customize_glob:
    input_boolean.*:
      homebridge_hidden: false
  
    device_tracker.*:
      homebridge_hidden: false



#ios:

input_text:
  weekday_bedtime_on:
    name: Weekday bedtime mode on
    min: 5
    max: 5
    icon: mdi:clock
    pattern: '([0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]'

  weekday_bedtime_off:
    name: Weekday bedtime mode off
    min: 5
    max: 5
    icon: mdi:clock
    pattern: '([0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]'

  weekend_bedtime_on:
    name: Weekend bedtime mode on
    min: 5
    max: 5
    icon: mdi:clock
    pattern: '([0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]'

  weekend_bedtime_off:
    name: Weekend bedtime mode off
    min: 5
    max: 5
    icon: mdi:clock
    pattern: '([0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]'


device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: true
    mqtt_topic: "owntracks/#"


input_boolean:
  away_mode:
    name: Away mode
    icon: mdi:car

  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup

  holiday_mode:
    name: Holiday mode
    icon: mdi:airplane

  bedtime_mode:
    name: Bedtime mode
    icon: mdi:sleep


group:
  phone_trackers:
    name: Phone Trackers
    entities:
      - device_tracker.mattiphoneowntrk_iphone
  occupancy:
    name: Occupancy Settings
    entities:
      - input_text.weekday_bedtime_on
      - input_text.weekday_bedtime_off
      - input_text.weekend_bedtime_on
      - input_text.weekend_bedtime_off
      - input_boolean.away_mode
      - input_boolean.guest_mode
      - input_boolean.holiday_mode
      - input_boolean.bedtime_mode

alert:
  guest_mode_alert:
    name: Guest Mode has been on for a long time
    done_message: Guest Mode de-activated
    entity_id: input_boolean.guest_mode
    repeat:
      - 240
      - 120
    skip_first: true
    notifiers:
      - matt

sensor:
  platform: template
  sensors:
    home_status:
      friendly_name: Home status
      value_template: >
        {%- if is_state('group.phone_trackers' , 'home') or is_state('input_boolean.guest_mode' , 'on') -%} Occupied
        {%- else -%} Unoccupied {%- endif -%}


automation:
  - alias: Occupancy - Set Weekend Bedtime Mode When Lounge TV Turns Off
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_tv_operation_state
      from: 'on'
      to: 'off'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - fri
            - sat
        - condition: template
          value_template: "{{ now().time() > strptime(states.input_text.weekend_bedtime_on.state, '%H:%M').time() }}"
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

automation:
  - alias: Occupancy - Set Weekend Bedtime Mode When Lounge TV Turns Off (late)
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_tv_operation_state
      from: 'on'
      to: 'off'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: template
          value_template: "{{ now().time() < strptime(states.input_text.weekend_bedtime_off.state, '%H:%M').time() }}"
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

  - alias: Occupancy - Set Weekday Bedtime Mode When Lounge TV Turns Off
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_tv_operation_state
      from: 'on'
      to: 'off'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sun
            - mon
            - tue
            - wed
            - thu
        - condition: template
          value_template: "{{ now().time() > strptime(states.input_text.weekend_bedtime_on.state, '%H:%M').time() }}"
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

automation:
  - alias: Occupancy - Set Weekday Bedtime Mode When Lounge TV Turns Off (late)
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_tv_operation_state
      from: 'on'
      to: 'off'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: "{{ now().time() < strptime(states.input_text.weekend_bedtime_off.state, '%H:%M').time() }}"
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

  - alias: Occupancy - Return home
    initial_state: on
    trigger:
      platform: state
      entity_id: group.phone_trackers
      to: 'home'
    action:
      service: homeassistant.turn_off
      entity_id:
        - input_boolean.guest_mode
        - input_boolean.away_mode
        - input_boolean.holiday_mode

  - alias: Occupancy - Nobody home
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
      for:
        minutes: 5
    action:
      - service: homeassistant.turn_on
        entity_id:
          - input_boolean.away_mode
          - script.empty_bedroom
          - script.empty_girls
          - script.empty_boys

  - alias: Occupancy - Holiday Mode
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
      for:
        hours: 24
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.holiday_mode
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.away_mode

  - alias: Occupancy - Weekday Bedtime Mode On
    initial_state: on
    trigger:
      - platform: template
        value_template: '{{ states.sensor.time.state == states.input_text.weekday_bedtime_on.state }}'
    condition:
      condition: and
      conditions:    
        - condition: time
          weekday:
            - sun
            - mon
            - tue
            - wed
            - thu
        - condition: state
          entity_id: binary_sensor.lounge_tv_operation_state
          state: 'off'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.bedtime_mode

  - alias: Occupancy - Weekday Bedtime Mode Off
    initial_state: on
    trigger:
      - platform: template
        value_template: '{{ states.sensor.time.state == states.input_text.weekday_bedtime_off.state }}'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.bedtime_mode

  - alias: Occupancy - Weekend Bedtime Mode On
    initial_state: on
    trigger:
      - platform: template
        value_template: '{{ states.sensor.time.state == states.input_text.weekend_bedtime_on.state }}'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - fri
            - sat
        - condition: state
          entity_id: binary_sensor.lounge_tv_operation_state
          state: 'off'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.bedtime_mode

  - alias: Occupancy - Weekend Bedtime Mode Off
    initial_state: on
    trigger:
      - platform: template
        value_template: '{{ states.sensor.time.state == states.input_text.weekend_bedtime_off.state }}'
    condition:
      - condition: time
        weekday:
          - sat
          - sun
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.bedtime_mode