####################################################
#                                                  #
# This package creates a device that monitors who  #
# is at home, including a guest mode, and provides #
# modes that assist with automations.              #
#                                                  #
#  Depends on: Hardware                            #
####################################################

homeassistant:
  customize:
    group.all_automations:
      friendly_name: Automations
      icon: mdi:home-automation
      hidden: false
      hide_control: true
    binary_sensor.home_occupied:
      icon: mdi:home-map-marker
    input_boolean.holiday_mode:
      hide_control: true
      extra_badge:
        entity_id: input_boolean.holiday_mode
    binary_sensor.lounge_occupied:
      device_class: occupancy

input_datetime:
  weekday_bedtime_on:
    name: Weekday bedtime on
    icon: mdi:clock
    has_date: false
    has_time: true
  weekday_bedtime_off:
    name: Weekday bedtime off
    icon: mdi:clock
    has_date: false
    has_time: true
  weekend_bedtime_on:
    name: Weekend bedtime on
    icon: mdi:clock
    has_date: false
    has_time: true
  weekend_bedtime_off:
    name: Weekend bedtime off
    icon: mdi:clock
    has_date: false
    has_time: true

input_boolean:
  away_mode:
    name: Away mode
    icon: mdi:car
  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup
  holiday_mode:
    name: Holiday mode
    icon: mdi:airplane
  bedtime_mode:
    name: Bedtime mode
    icon: mdi:sleep

input_number:
  lounge_occupancy_idle_minutes:
    initial: 30
    min: 0
    max: 120
    step: 1

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"

group:
  phone_trackers:
    name: Phone Trackers
    entities:
      - device_tracker.mattiphoneowntrk_iphone
      - device_tracker.beliphoneowntrk_iphone
      
alert:
  guest_mode_alert:
    name: Guest Mode has been on for a long time
    done_message: Guest Mode de-activated
    entity_id: input_boolean.guest_mode
    repeat:
      - 240
      - 120
    skip_first: true
    notifiers:
      - matt

binary_sensor:
  - platform: template
    sensors:
      home_occupied:
        friendly_name: Home Occupied
        entity_id:
          - group.phone_trackers
          - input_boolean.guest_mode
        device_class: occupancy
        value_template: >-
          {{- is_state('group.phone_trackers', 'home')
            or 
          is_state('input_boolean.guest_mode' , 'on') -}}
      lounge_recent_motion:
        friendly_name: Lounge recent motion
        entity_id:
          - binary_sensor.lounge_multi_sensor_motion
          - sensor.time
          - input_number.lounge_occupancy_idle_minutes
        device_class: occupancy
        value_template: >-
          {{- (as_timestamp(now())
            - 
          as_timestamp(states.binary_sensor.lounge_multi_sensor_motion.last_changed))
            <=
          (states('input_number.lounge_occupancy_idle_minutes') | float * 60)
          -}}
      lounge_occupied:
        friendly_name: Lounge occupied
        entity_id:
          - media_player.lounge_tv
          - media_player.lounge_hifi
          - binary_sensor.lounge_recent_motion
        value_template: >-
          {{- is_state('media_player.lounge_tv','playing')
            or
          is_state('media_player.lounge_hifi','playing')
            or
          is_state('binary_sensor.lounge_recent_motion','on') -}}

automation:
  - alias: Occupancy - Set Weekend Bedtime Mode When Lounge No Longer Occupied
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_occupied
      from: 'on'
      to: 'off'
      for: '00:10:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - fri
            - sat
        - condition: template
          value_template: >-
            {{ states('sensor.time')
              >
            (states.input_datetime.weekend_bedtime_on.attributes.timestamp
              | int |
            timestamp_custom('%H:%M', False)) }}
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

  - alias: Occupancy - Set Weekend Bedtime Mode When Lounge TV Turns Off (late)
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_occupied
      from: 'on'
      to: 'off'
      for: '00:10:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: template
          value_template: >-
            {{ states('sensor.time')
              <
            (states.input_datetime.weekend_bedtime_off.attributes.timestamp
              | int |
            timestamp_custom('%H:%M', False)) }}
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

  - alias: Occupancy - Set Weekday Bedtime Mode When Lounge TV Turns Off
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_occupied
      from: 'on'
      to: 'off'
      for: '00:10:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sun
            - mon
            - tue
            - wed
            - thu
        - condition: template
          value_template: >-
            {{ states('sensor.time')
              >
            (states.input_datetime.weekday_bedtime_on.attributes.timestamp
              | int |
            timestamp_custom('%H:%M', False)) }}
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

  - alias: Occupancy - Set Weekday Bedtime Mode When Lounge TV Turns Off (late)
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.lounge_occupied
      from: 'on'
      to: 'off'
      for: '00:10:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: >- 
            {{ states('sensor.time')
              <
            (states.input_datetime.weekday_bedtime_off.attributes.timestamp
              | int |
            timestamp_custom('%H:%M', False)) }}
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedtime_mode

  - alias: Occupancy - Return home
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.home_occupied
      to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.away_mode
          - input_boolean.holiday_mode

  - alias: Occupancy - Nobody home
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.home_occupied
      to: 'off'
      for:
        minutes: 5
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.away_mode

  - alias: Occupancy - Holiday Mode
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
      for:
        hours: 24
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.holiday_mode

  - alias: Occupancy - Weekday Bedtime Mode On
    initial_state: on
    trigger:
      - platform: template
        value_template: >-
          {{- states('sensor.time')
            == 
          (states.input_datetime.weekday_bedtime_on.attributes.timestamp
            | int |
          timestamp_custom('%H:%M', False)) -}}
    condition:
      condition: and
      conditions:    
        - condition: time
          weekday:
            - sun
            - mon
            - tue
            - wed
            - thu
        - condition: state
          entity_id: binary_sensor.lounge_occupied
          state: 'off'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.bedtime_mode

  - alias: Occupancy - Weekday Bedtime Mode Off
    initial_state: on
    trigger:
      - platform: template
        value_template: >-
          {{- states('sensor.time')
            == 
          (states.input_datetime.weekday_bedtime_off.attributes.timestamp
            | int |
          timestamp_custom('%H:%M', False)) -}}
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.bedtime_mode

  - alias: Occupancy - Weekend Bedtime Mode On
    initial_state: on
    trigger:
      - platform: template
        value_template: >-
          {{- states('sensor.time')
            == 
          (states.input_datetime.weekend_bedtime_on.attributes.timestamp
            | int |
          timestamp_custom('%H:%M', False)) -}}
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - fri
            - sat
        - condition: state
          entity_id: binary_sensor.lounge_occupied
          state: 'off'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.bedtime_mode

  - alias: Occupancy - Weekend Bedtime Mode Off
    initial_state: on
    trigger:
      - platform: template
        value_template: >-
          {{- states('sensor.time')
            == 
          (states.input_datetime.weekend_bedtime_off.attributes.timestamp
            | int |
          timestamp_custom('%H:%M', False)) -}}
    condition:
      - condition: time
        weekday:
          - sat
          - sun
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.bedtime_mode

  - alias: Occupancy - Reset Guest mode at midnight
    trigger:
      - platform: time
        at: '00:00:00'
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.guest_mode