####################################################
#                                                  #
# This package creates a device that monitors who  #
# is at home, including a guest mode, and provides #
# modes that assist with automations.              #
#                                                  #
#  Depends on: Hardware                            #
####################################################

homeassistant:
  customize:
    group.all_automations:
      friendly_name: Automations
      icon: mdi:home-automation
      hidden: false
      hide_control: true
    binary_sensor.home_occupied:
      icon: mdi:home-map-marker
    input_boolean.holiday_mode:
      hide_control: true
      extra_badge:
        entity_id: input_boolean.holiday_mode
    binary_sensor.lounge_occupied:
      device_class: occupancy

input_datetime:
  weekday_bedtime_on:
    name: Weekday bedtime on
    icon: mdi:clock
    has_date: false
    has_time: true
  weekday_bedtime_off:
    name: Weekday bedtime off
    icon: mdi:clock
    has_date: false
    has_time: true
  weekend_bedtime_on:
    name: Weekend bedtime on
    icon: mdi:clock
    has_date: false
    has_time: true
  weekend_bedtime_off:
    name: Weekend bedtime off
    icon: mdi:clock
    has_date: false
    has_time: true

input_boolean:
  away_mode:
    name: Away mode
    icon: mdi:car
  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup
  holiday_mode:
    name: Holiday mode
    icon: mdi:airplane
  bedtime_mode:
    name: Bedtime mode
    icon: mdi:sleep

input_number:
  lounge_occupancy_idle_minutes:
    initial: 30
    min: 0
    max: 120
    step: 1

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"

group:
  phone_trackers:
    name: Phone Trackers
    entities:
      - device_tracker.mattiphoneowntrk_iphone
      - device_tracker.beliphoneowntrk_iphone
      
alert:
  guest_mode_alert:
    name: Guest Mode has been on for a long time
    done_message: Guest Mode de-activated
    entity_id: input_boolean.guest_mode
    repeat:
      - 240
      - 120
    skip_first: true
    notifiers:
      - matt

binary_sensor:
  - platform: template
    sensors:
      home_occupied:
        friendly_name: Home Occupied
        entity_id:
          - group.phone_trackers
          - input_boolean.guest_mode
        device_class: occupancy
        value_template: >-
          {{- is_state('group.phone_trackers', 'home')
            or 
          is_state('input_boolean.guest_mode' , 'on') -}}
      lounge_recent_motion:
        friendly_name: Lounge recent motion
        entity_id:
          - binary_sensor.lounge_multi_sensor_motion
          - sensor.time
          - input_number.lounge_occupancy_idle_minutes
        device_class: occupancy
        value_template: >-
          {{- (as_timestamp(now())
            - 
          as_timestamp(states.binary_sensor.lounge_multi_sensor_motion.last_changed))
            <=
          (states('input_number.lounge_occupancy_idle_minutes') | float * 60)
          -}}
      lounge_occupied:
        friendly_name: Lounge occupied
        entity_id:
          - media_player.lounge_tv
          - media_player.lounge_hifi
          - binary_sensor.lounge_recent_motion
        value_template: >-
          {{- is_state('media_player.lounge_tv','playing')
            or
          is_state('media_player.lounge_hifi','playing')
            or
          is_state('binary_sensor.lounge_recent_motion','on') -}}