camera:
  - platform: ffmpeg
    name: dafang1
    input: !secret camera1_input
    
binary_sensor:
  - platform: mqtt
    name: Hallway Motion Sensor
    state_topic: smartthings/Hallway Motion Sensor/motion/state
    payload_on: active
    payload_off: inactive
    device_class: motion
    retain: true

  - platform: mqtt
    name: Front Door Motion
    state_topic: smartthings/Front Door/motion/state
    payload_on: active
    payload_off: inactive
    device_class: motion
    retain: true


ring:
  username: !secret ring_user
  password: !secret ring_password


sensor:
  - platform: ring