
sensor:
  - platform: mqtt
    name: Hallway Temperature
    state_topic: smartthings/Hallway Motion Sensor/temperature/status
    device_class: temperature
    retain: true

camera:
  - platform: ffmpeg
    name: dafang1
    input: -rtsp_transport tcp -i rtsp://172.30.1.60:8554/unicast
    
binary_sensor:
  - platform: mqtt
    name: Hallway Motion Sensor
    state_topic: smartthings/Hallway Motion Sensor/motion/state
    payload_on: active
    payload_off: inactive
    device_class: motion
    retain: true

  - platform: mqtt
    name: Front Door Motion
    state_topic: smartthings/Front Door/motion/state
    payload_on: active
    payload_off: inactive
    device_class: motion
    retain: true