homeassistant:
  customize:
    sensor.ring_hallway_volume:
      friendly_name: Hallway Ring Chime Volume
    
    sensor.ring_hallway_wifi_signal_category:
      friendly_name: Hallway Ring Chime WiFi Signal Category
    
    sensor.ring_hallway_wifi_signal_strength:
      friendly_name: Hallway Ring Chime WiFi Signal Strength

camera:
  - platform: ring
    
binary_sensor:
  - platform: mqtt
    name: Hallway Motion Sensor
    state_topic: smartthings/Hallway Motion Sensor/motion/state
    payload_on: active
    payload_off: inactive
    device_class: motion
    retain: true
    
  - platform: ring

ring:
  username: !secret ring_user
  password: !secret ring_password

sensor:
  - platform: ring