homeassistant:
  customize:
    sensor.ring_hallway_volume:
      friendly_name: Hallway Ring Chime Volume
    
    sensor.ring_hallway_wifi_signal_category:
      friendly_name: Hallway Ring Chime WiFi Signal Category
    
    sensor.ring_hallway_wifi_signal_strength:
      friendly_name: Hallway Ring Chime WiFi Signal Strength
    
    binary_sensor.hallway_motion_sensor:
      homebridge_visible: true
     
    sensor.ring_front_door_last_motion:
      homebridge_visible: true

    sensor.ring_front_door_last_ding:
      homebridge_visible: true
    
    camera.front_door:
      homebridge_visible: true


camera:
  - platform: ffmpeg
    name: dafang1
    input: !secret camera1_input
  - platform: ring
    
binary_sensor:
  - platform: mqtt
    name: Hallway Motion Sensor
    state_topic: smartthings/Hallway Motion Sensor/motion/state
    payload_on: active
    payload_off: inactive
    device_class: motion
    retain: true
    
  - platform: ring


ring:
  username: !secret ring_user
  password: !secret ring_password

sensor:
  - platform: ring