############################################
#                                          #
#  This include defines what is logged in  #
#  the systems logbook and history pages   #
#                                          #
############################################

include:
  domains:
    - light
    - binary_sensor
    - device_tracker
    - switch
    - sensor
    - climate
    - media_player
    - sun
    - input_boolean
    - input_datetime
    - input_text

exclude:
  entities:
    - binary_sensor.random_binary_sensor
    - sensor.time
    - sensor.time_utc
    - sensor.date
    - sensor.loungedimmer_interval
    - sensor.loungedimmer_interval_2
    - sensor.loungedimmer_interval_3
    - sensor.loungedimmer_interval_4