########################################################
#                                                      #
# This package contains automations that respond to    #
# interactive commands by actioning the request        #
#                                                      #
# DEPENDS ON: Notifications                            #
#                                                      #
########################################################


automation:

  - alias: Telegram - Holiday mode toggle
    initial_state: on
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/holiday'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.holiday_mode
      - service: telegram_bot.send_message
        data_template:
          target: "{{ trigger.event.data.user_id }}"
          message: "Holiday mode has been turned {{ states('input_boolean.holiday_mode') }}"

  - alias: Telegram - Guest mode toggle
    initial_state: on
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/guest'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.guest_mode
      - service: telegram_bot.send_message
        data_template:
          target: "{{ trigger.event.data.user_id }}"
          message: "Guest mode has been turned {{ states('input_boolean.guest_mode') }}."

  - alias: Telegram - Away mode
    initial_state: on
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/away'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.away_mode
      - service: telegram_bot.send_message
        data_template:
          target: "{{ trigger.event.data.user_id }}"
          message: "Away mode has been turned {{ states('input_boolean.away_mode') }}."