group:
  environment_view:
    name: Environment
    icon: mdi:temperature-celcius
    view: yes
    entities: 
      - group.nest
      - group.sensors

  nest:
    name: Nest
    entities:
    - binary_sensor.hallway_thermostat_fan
    - binary_sensor.hallway_thermostat_has_leaf
    - binary_sensor.hallway_thermostat_is_locked
    - binary_sensor.hallway_thermostat_is_using_emergency_heat
    - binary_sensor.hallway_thermostat_online
    - climate.hallway
    - sensor.hallway_thermostat_humidity
    - sensor.hallway_thermostat_hvac_state
    - sensor.hallway_thermostat_operation_mode
    - sensor.hallway_thermostat_target
    - sensor.hallway_thermostat_temperature
  
  sensors:
    name: Sensors
    entities:
    - sensor.hallway_temperature
    - binary_sensor.hallway_motion_sensor
    - binary_sensor.front_door_motion
    - binary_sensor.wildown_gardens_away
    - sensor.wildown_gardens_eta
