group:
  security_view:
    name: Security
    icon: mdi:cctv
    view: yes
    entities: 
      - group.ring
      - group.security_sensors

  ring:
    name: Ring
    entities:
      - sensor.ring_hallway_wifi_signal_strength
      - sensor.ring_hallway_wifi_signal_category
      - sensor.ring_hallway_volume
      - sensor.ring_front_door_wifi_signal_strength
      - sensor.ring_front_door_wifi_signal_category
      - sensor.ring_front_door_volume
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_activity
      - sensor.ring_front_door_battery
      - sensor.wildown_gardens_security_state
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - camera.front_door
  
  security_sensors:
    name: Security Sensors
    entities:
      - binary_sensor.hallway_motion_sensor
      - binary_sensor.home_occupied