name: configtest

on:
  push:
    branches: 
    - master

jobs:
  testconfig:
    name: Test HA configuration
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Copy dummy secrets.yaml
      run: cp ./extras/dummy_secrets/dummy_secrets.yaml ./secrets.yaml
    - name: Create dummy certificate files
      run: |
        touch cert.pem
        touch key.pem
    - name: Docker login
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username '${{ secrets.DOCKER_USERNAME }}' --password-stdin
