name: configtest

on: push

jobs:
  runtest:
    name: Test HA configuration
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: ls & pwd
      run: |
        ls -l
        pwd
    - name: Copy dummy secrets.yaml
      run: cp ./extras/dummy_secrets/dummy_secrets.yaml ./secrets.yaml
    - name: Create dummy certificate files
      run: |
        touch ./cert.pem
        touch ./key.pem
    - name: Docker login
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username '${{ secrets.DOCKER_USERNAME }}' --password-stdin
    - name: Pull Home Assistant container image
      run: docker pull homeassistant/home-assistant
    - name: Run container with test config switch
      run: docker run --rm --name ha --volume ./:/config homeassistant/home-assistant 'python -m homeassistant --config /config --script check_config'
