###########################################################
#                                                         #
# This package contains the components and sensors I use  #
# to monitor the Homeassistant software and system itself #
#                                                         #
###########################################################

recorder:
  purge_interval: 1
  purge_keep_days: 7
  db_url: !secret mariadb_url

logbook: !include ../../extras/includes/logging.yaml

history: !include ../../extras/includes/logging.yaml

logger:
  default: critical
#  logs:
#    homeassistant.components.component: info

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: last_boot
      - type: processor_use

automation:
  - alias: Device - Disk use alarm
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use_percent
      above: 85
    action:
      service: script.notify
      data:
        tell: matt
        no_say: 1
        call_hdd_space: 1

  - alias: Device - System load alarm
    initial_state: on
    trigger:
      - platform: numeric_state
        entity_id: sensor.processor_use
        above: 80
        for:
          minutes: 5
      - platform: numeric_state
        entity_id: sensor.memory_use_percent
        above: 85
    action:
      service: script.notify
      data:
        tell: matt
        no_say: 1
        call_system_load: 1
        
  - alias: Device - Power on
    initial_state: on
    trigger:
      platform: homeassistant
      event: start
    action:
      service: script.notify
      data:
        call_power_on: 1
        tell: matt
  
