###########################################
#                                         #
# This package contains the components,   #
# and sensors for monitoring the hardware #
# I have connected to my homeassistant    #
#                                         #
###########################################


homeassistant:
  customize_glob:
    media_player.*:
      icon: mdi:play



#zwave:
  #usb_path: /dev/ttyACM0
  #network_key: !secret zwave_network_key
  #autoheal: false


#hue:
  #bridges:
    #- host: !secret hue_hub_ip
    #  allow_unreachable: true


#light:
  #platform: flux_led
  #devices: !secret flux_led_devices


media_player:
  - platform: cast
  - platform: sonos
    host: !secret sonos_kitchen_ip


mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_hassio
  password: !secret mqtt_password_hassio
  discovery: true
  discovery_prefix: homeassistant

cloud: