###########################################
#                                         #
# This package contains the components,   #
# and sensors for monitoring the hardware #
# I have connected to my homeassistant    #
#                                         #
###########################################


homeassistant:
  customize_glob:
    media_player.*:
      icon: mdi:play

wake_on_lan:

media_player:
  - platform: webostv
    name: Lounge TV
    host: !secret lounge_tv_ip
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lounge_tv_mac

sensor:
  - platform: mqtt
    name: Lounge Lamp Energy Usage
    state_topic: smartthings/Lounge Lamp/power/state
    unit_of_measurement: W
    icon: mdi:power-socket-uk
    retain: 
    
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_utc'

switch:
  - platform: mqtt
    name: Lounge Lamp
    command_topic: 'smartthings/Lounge Lamp/switch/cmd'
    state_topic: 'smartthings/Lounge Lamp/switch/state'
    payload_on: 'on'
    payload_off: 'off'
    icon: mdi:lightbulb
    retain: true

group:
  date_time:
    name: Date and Time
    icon: mdi:calendar-clock
    entities:
      - sensor.time
      - sensor.date
      - sensor.time_utc


zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  autoheal: false


mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_hassio
  password: !secret mqtt_password_hassio
  discovery: true
  discovery_prefix: homeassistant