###########################################
#                                         #
# This package contains the components,   #
# and sensors for monitoring the hardware #
# I have connected to my homeassistant    #
#                                         #
###########################################

homeassistant:
  customize:
    binary_sensor.lounge_multi_sensor_motion:
      device_class: motion
    sensor.lounge_multi_sensor_luminance:
      device_class: illuminance
  
  customize_glob:
    media_player.*:
      icon: mdi:play

stream:

wake_on_lan:

media_player:
  - platform: webostv
    name: Lounge TV
    host: !secret lounge_tv_ip
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lounge_tv_mac

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_utc'

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  autoheal: false


mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_hassio
  password: !secret mqtt_password_hassio
  discovery: true
  discovery_prefix: homeassistant