###########################################
#                                         #
# This package contains the components,   #
# and sensors for monitoring the hardware #
# I have connected to my homeassistant    #
#                                         #
###########################################


homeassistant:
  customize_glob:
    media_player.*:
      icon: mdi:play


sensor:
  - platform: mqtt
    name: Lounge TV Energy Usage
    state_topic: smartthings/Lounge TV Outlet/power/state
    unit_of_measurement: W
    icon: mdi:power-socket-uk
    retain: true

switch:
  - platform: mqtt
    name: Lounge TV Switch
    command_topic: 'smartthings/Lounge TV Outlet/switch/cmd'
    state_topic: 'smartthings/Lounge TV Outlet/switch/state'
    payload_on: 'on'
    payload_off: 'off'
    icon: mdi:power-socket-uk
    retain: true

binary_switch:
  - platform: template
    sensors:
      lounge_tv_operation_state:
      name: Lounge TV operation state
      icon: mdi:television
      device_class: power
      value_template: >-
        {%- if (states.sensor.lounge_tv_energy_usage.state | float < 50 ) -%}
          off
        {%- else -%}
          on
        {%- endif -%}


#zwave:
  #usb_path: /dev/ttyACM0
  #network_key: !secret zwave_network_key
  #autoheal: false


#hue:
  #bridges:
    #- host: !secret hue_hub_ip
    #  allow_unreachable: true


#light:
  #platform: flux_led
  #devices: !secret flux_led_devices


#media_player:
#  - platform: cast
#  - platform: sonos
#    host: !secret sonos_kitchen_ip


mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_hassio
  password: !secret mqtt_password_hassio
  discovery: true
  discovery_prefix: homeassistant

#cloud: