################################################
#                                              #
# This package creates a device that allows me #
# to set a boolean to show the system in       #
# "Maintenance Mode", and manage backing up,   #
# upgrading and pulling config from Github     #
#                                              #
################################################


homeassistant:
  customize_glob:
    weblink.*:
      icon: mdi:web

  customize:
    script.zwave_on:
      icon: mdi:check-circle-outline
      custom_text: Z-Wave On

    script.zwave_off:
      icon: mdi:close-octagon-outline
      custom_text: Z-Wave Off

    script.zwave_include:
      icon: mdi:plus-circle-outline
      custom_text: "Add New Device (Secure)"
    
    script.github_pull:
      icon: mdi:github-box
      custom_text: Github pull
    
    script.restart_ha:
      icon: mdi:home-assistant
      custom_text: Restart Home Assistant

input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:auto-fix

alert:
  maintenance_mode_alert:
    name: Maintenance Mode has been on for a long time
    done_message: Maintenance Mode de-activated
    entity_id: input_boolean.maintenance_mode
    repeat:
      - 60
    skip_first: true
    notifiers:
      - matt

script:
  zwave_on:
    alias: Z-Wave Start Network
    sequence:
      - service: zwave.start_network

  zwave_off:
    alias: Z-Wave Stop Network
    sequence:
      - service: zwave.stop_network

  zwave_include:
    alias: Z-Wave Add Node (Secure)
    sequence:
      - service: zwave.add_node_secure
    
  github_pull:
    alias: Github Pull
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.maintenance_mode
      - service: hassio.addon_restart
        data:
          addon: core_git_pull
  
  restart_ha:
    alias: Restart HA
    sequence:
      - service: homeassistant.restart

automation:
  - alias: github_pull_webhook
    trigger:
      platform: webhook
      webhook_id: 6e290ed425a4cede391488c8e7c6e06d87055120809c4c1376091eaf1d47eb30
    action:
      - service: script.turn_on
        entity_id: script.github_pull
